### ISSUE TITLE
Messages Icon?

### ISSUE THREAD

**Issue by Daniel-McGuire** [snwh/suru-icons#1]
Hi Sam, 

I'm going to be using these icons for /r/Ubuntu on reddit, will you be making a 'messages' icon as seen on the messages app on the phone? I was hoping to use it for the icon for self-posts.

Thanks!

**Comment by snwh** [comment]
I think you're looking for this repo: https://github.com/snwh/suru-icon-theme

**Comment by Daniel-McGuire** [comment]
Blast! Didn't know there was a different repo. Cheers!
